client.go

This being a library we should prevent logging (per default). Since this is the only log call currently I've decided to simply comment it out. If we want to use a logger, we need to provide a way for the library's user to overwrite the logger.

Remove log call

---

.github/workflows/build.yml
.github/workflows/generate.yml

Adds two GitHub Action workflow that run for every push and pull request.
The first one tries to build the entire project on Ubuntu, macOS, and Windows for Go 1.11 (minimum required version) as well as the latest available Go version (at the time of the action being run). It will also run `go test` should we have test cases in the future. Currently it will just silently pass as it doesn't find any.
The second one runs the generator (`make generate`) on Ubuntu and tries to build the project with the freshly generated sources.

Add Go build/test workflow

---

client.go
e2e/e2e_test.go

Changes:
- Adds `WithDialer(x *websocket.Dialer)` and `WithRequestHeader(x http.Header)` options. Addresses #23.
- Sets the default request headers to have a user agent of `goobs/${version}`. Example log from OBS with this library now:
```[connect] WebSocket Connection 192.168.200.1:41272 v13 "goobs/0.8.0-dev" / 101```
Note: This necessitates maintaining the library version within the code now. So, before a release, this should be updated to remove the `-dev` suffix, and then bumped up in preparation for the next release.

Add configurable underlying dialer and request header options

---

api/requests/client.go
api/requests/requests.go
client.go

Changes:
- Configurable timeout for responses. Should a request not receive a response after the timeout, we return an error.
This is client-wide. Default is 10 seconds.
- Don't panic on unrecognized messages, rather expose as errors. Closes #22.
- Improves authentication error handling.
- Maintain the latest events broadcast by OBS in order. Still available via `client.IncomingEvents`. Previously this just stored the first 100 if they weren't yet consumed.
Plus just general housekeeping.

Improves error handling

---

client.go

When the connection is closed from OBS side `handleConnection()` needs to stop trying to call `ReadJSON()`. Otherwise the underlying websocket package panics with `panic: repeated read on failed websocket connection`.
I'm not completely sure if this is the right approach to handle this issue. It works pretty well for me by listening to errors and recreating the goobs instance in this case.

Fix panic on connection close

---

client.go
internal/generate/tests/main.go
test.sh
zz_generated._test.go

When wrong password was specified, `goobs.New()` didn't return.

client: error out when authentication failed

---

client.go
internal/generate/tests/main.go
zz_generated._test.go

When server is not running, `goobs.New()` panics.

client: don't panic if server is not running

---

client.go

This change is not important. Just a small improvement.
I noticed that obs-websocket server closes the version check connection [5 seconds after version check](https://obsproject.com/logs/WqaE0o11v0W23Flw). Probably according to the value of `timeout_close_handshake` from [websocketpp](https://docs.websocketpp.org/reference_8config.html).
After this change, version check connection [closes immediately](https://obsproject.com/logs/REiWYw7pBgjqyRkJ).

client: close protocol version check connection

---

README.md
api/events/xx_generated.general.customevent.go
api/events/xx_generated.inputs.inputvolumechanged.go
api/events/xx_generated.ui.screenshotsaved.go
api/events/zz_generated.events.go
api/requests/general/xx_generated.sleep.go
api/requests/inputs/xx_generated.pressinputpropertiesbutton.go
api/requests/outputs/xx_generated.getoutputlist.go
api/requests/record/xx_generated.getrecordstatus.go
api/requests/sceneitems/xx_generated.getgroupsceneitemlist.go
version.go

Guess there's no new stuff. Surprised there's no breaking changes!
For posterity, release process was as follows:
1. Bump `goobs_version` and `obs_protocol_version` in `version.go`
2. Run `make clean && make generate` to pull in latest protocol changes
3. Ensure no tests are failing via `make test`, modifying `internal/generate/tests/main.go` if necessary
4. Double check the versions from step 1, and merge the PR in
5. Back on the main branch, pull in the latest changes and run `make release`
6. View and edit the release from the Web UI if necessary (I like to add the corresponding `obs-websocket` protocol version to the name of the release)

obs websocket v5.1.0

---

api/client.go
client_test.go
internal/generate/tests/main.go
test.sh
zz_generated._test.go

fix multi-goroutine bug and add multi-goroutine request test
```
1. panic: concurrent write to websocket connection
2. request GetSceneList: mismatched ID: expected response with ID c30f63f4-0065-4cb0-5873-19e12a676ee1, but got 97362273-a871-415b-6610-45894239012e
```

fix multi-goroutine request error

---

api/client.go
client.go

For efficiency, cancel time.Timer after no longer needed. See https://pkg.go.dev/time#After
Note on behavior change:
timeout duration <= 0 now means waiting forever instead of immediately times out..

Use `time.NewTimer()` instead of `time.After()`

---

README.md
api/client.go
client.go
client_test.go
test.sh

In cases of highly concurrent clients, there seems to be some bugs when disconnecting and still trying to write to the closed websocket connection or to the internal channels used. These added checks should hopefully prevent most of those panics. 🤞
For some reason this was more prevalent when using gorilla/websocket v1.5.1 instead of v1.5.0 (https://github.com/andreykaipov/goobs/pull/64).
Also changes most of the DEBUG logs to TRACE logs.

client: handle disconnections better

---

.github/workflows/update-protocol-version.yml

Now that we're consuming the latest protocol version, the CI complains there's nothing to update. While the script should still return `exit 1`, the CI should be green for this cron workflow.

ci: capture exit 1 in update protocol workflow to cleanly exit

---

.github/workflows/release-drafter.yml

From the docs in https://github.com/release-drafter/release-drafter, I _think_ I need this to make the auto-labeling work for forks. 
This PR https://github.com/andreykaipov/goobs/pull/126 ran the `update-release-draft` workflow but silently failed with the following errors:
---
Would be nice to only update the release draft on PR close, and run the auto-labeler on other events, but don't think I can do that yet based on [this comment](https://github.com/release-drafter/release-drafter/issues/1125#issuecomment-1324160912)

ci: use gh app token for release-drafter

---

client.go
internal/generate/protocol/generate.go
internal/generate/tests/main.go
zz_generated.client.go

I don't automatically assume this is wanted / will be accepted. But I figured the change was easy enough to make that the discussion could be started with the PR.
Embedding a private struct creates the confusing effect of exporting the public fields of the embedded struct without having them show in documentation.
This has some discussion at the language / godoc level: https://github.com/golang/go/issues/6600
This commit exports the subclients field of `goobs.Client` so the available fields show in documentation.
I actually used this project as an example for how this behavior of godoc is confusing for developers: https://github.com/golang/go/issues/6600#issuecomment-1874538749

docs: export Subclients embedded struct

---

.github/workflows/image-retention-policy.yml

can't use gh app generated tokens in this action :(

ci: use github.token for image retention

---

.github/workflows/release-drafter.yml

Okay maybe https://github.com/andreykaipov/goobs/pull/127 wasn't the right fix. Shoulda stuck with the docs and just used the default github.token and not try to get fancy with gh app generated tokens...

ci: make release draft labeling work for forks

---

.github/workflows/image.yml
.gitignore
docker/.dockerignore
docker/Dockerfile
script/bump-protocol-version.sh
script/get-latest-obs.sh

Whenever obs-websocket releases a new minor version, the client library is auto generated, but if the minor version has new requests, the tests will fail because we're testing against the older version of the server, e.g. https://github.com/andreykaipov/goobs/pull/131
Since obs-websocket is bundled with OBS now, this PR gets the latest artifact from [obsproject/obs-studio's push workflow](https://github.com/obsproject/obs-studio/actions/workflows/push.yaml) and uses that instead of the PPA because it could be weeks until it's updated.
It also builds the image before bumping instead of on a weekly cadence. Hopefully the next time there's a minor version bump with new requests, this will automatically build the image, the generated protocol PR will be created, and the tests can pass.
~~This …

ci: use the latest OBS in Docker image

---

api/client.go
api/requests/record/xx_generated.togglerecordpause.go
api/typedefs/typedefs.go
go.mod
go.sum
internal/generate/protocol/generate.go
internal/sample/go.mod
internal/sample/go.sum
script/test.sh

First I'm adding mapstructure to error on unused fields returned by the obs-websocket server when decoding. This only happens when debugging (i.e. when `GOOBS_LOG` is nonempty).

fix: add missing UUIDs and fields on some resources

---

.github/dependabot.yml

might be noisy but stuff like this fails when it shouldn't https://github.com/andreykaipov/goobs/pull/157

ci: update both indirect and direct gomod deps for /internal/sample

---

client.go

This adds WSS support to _this library_ and closes https://github.com/andreykaipov/goobs/issues/167.
Since the obs-websocket server unfortunately doesn't support WSS (see https://github.com/obsproject/obs-websocket/issues/26), one would first need to setup a reverse proxy in front of the server to secure it. The obs-websocket folks have a guide here: https://github.com/obsproject/obs-websocket/wiki/SSL-Tunneling.

client: add wss support

---

.github/workflows/ci.yml
go.mod
internal/go.mod
internal/sample/go.mod
script/test.sh

CI is failing 🤷 
```golang.org/x/tools/internal/pkgbits: cannot compile Go 1.22 code
golang.org/x/tools/internal/tokeninternal: cannot compile Go 1.22 code
golang.org/x/mod/semver: cannot compile Go 1.22 code
golang.org/x/tools/internal/event/label: cannot compile Go 1.22 code
golang.org/x/tools/internal/stdlib: cannot compile Go 1.22 code
golang.org/x/tools/internal/aliases: cannot compile Go 1.22 code
golang.org/x/tools/internal/versions: cannot compile Go 1.22 code
```

use go 1.22

---

client.go

bugfix(client): Fix the panic due to concurrent writing
The bug:
```
panic: concurrent write to websocket connection
goroutine 66624 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc001ad7ef0, 0x1, {0x0?, 0x0?, 0x0?})
/home/streampanel/go/pkg/mod/github.com/gorilla/websocket@v1.5.3/conn.go:617 +0x4b8
github.com/gorilla/websocket.(*messageWriter).Close(0xc001e12f60?)
/home/streampanel/go/pkg/mod/github.com/gorilla/websocket@v1.5.3/conn.go:731 +0x35
github.com/gorilla/websocket.(*Conn).beginMessage(0xc001e034a0, 0xc001e12f60, 0x8)
/home/streampanel/go/pkg/mod/github.com/gorilla/websocket@v1.5.3/conn.go:480 +0x3a
github.com/gorilla/websocket.(*Conn).NextWriter(0xc001e034a0, 0x8)
/home/streampanel/go/pkg/mod/github.com/gorilla/websocket@v1.5.3/conn.go:520 +0x3f …
```

bugfix(client): Fix the panic due to concurrent writing

---

api/client.go
client.go

Fix:
panic: send on closed channel
goroutine 751872 [running]:
github.com/andreykaipov/goobs.(*Client).writeEvent(...)
/home/xaionaro/.gvm/pkgsets/go1.22.1/global/pkg/mod/github.com/andreykaipov/goobs@v1.4.1/client.go:363
github.com/andreykaipov/goobs.(*Client).handleOpcodes(0xc0020c81a0, 0xc0013846c0)
/home/xaionaro/.gvm/pkgsets/go1.22.1/global/pkg/mod/github.com/andreykaipov/goobs@v1.4.1/client.go:338 +0x5a5
created by github.com/andreykaipov/goobs.(*Client).connect in goroutine 751658
/home/xaionaro/.gvm/pkgsets/go1.22.1/global/pkg/mod/github.com/andreykaipov/goobs@v1.4.1/client.go:200
Essentially by design we should close a channel only after we finished all possible writing to it. Thus moving the close statement of channel IncomingResponses to be called right after the writer to the …

bugfix(client): panic: send on closed channel

---

go.mod
internal/go.mod
internal/sample/go.mod

This PR removes the CI failures that were occurring due to:
```text
go: updates to go.mod needed; to update it:
go mod tidy
make: *** [Makefile:13: test.unit] Error 1
```
Based on the discussion in <https://github.com/golang/go/issues/62278#issuecomment-1698829945> and the fact that this project doesn't seem to rely on any specific patch revision, I put `1.23.0` to resolve the issue.

Fix build: Add patch version to go directive in go.mod

---

api/typedefs/typedefs.go

Fixes https://github.com/andreykaipov/goobs/issues/194
These are the correct types and annotations for KeyModifiers.
I was able to verify that this works with a small test program:
```go
params := general.NewTriggerHotkeyByKeySequenceParams()
params = params.WithKeyId("OBS_KEY_NUMPLUS")
params = params.WithKeyModifiers(&typedefs.KeyModifiers{Shift: true, Control: true, Alt: true})
if _, err := client.General.TriggerHotkeyByKeySequence(params); err != nil {
panic(err)
}
time.Sleep(1 * time.Second)
params2 := general.NewTriggerHotkeyByKeySequenceParams()
params2 = params.WithKeyId("OBS_KEY_NUMPLUS")
params2 = params.WithKeyModifiers(&typedefs.KeyModifiers{Shift: true, Control: true, Command: true})
if _, err := client.General.TriggerHotkeyByKeySequence(params2); err != nil {
panic(err)
} …
```

fix: Set correct types and annotations for KeyModifiers
